[evm]

[evm.moonbase]
beneficiary = "0xf1fd5607b90f6c421db7313158baac170d4f053b"
block-confirmations = 0
chain-id = 1287
enabled = true
http-endpoint = "https://moonbeam.public.blastapi.io"
name = "moonbase"
private-key = "0xc086596a698603ae7428a61ced569cbc5fdc24ae91c341d692aad590febc4429"
ws-endpoint = "wss://wss.api.moonbeam.network"

[[evm.moonbase.contracts]]
address = "0x72320f338706e0249045d0be06227f72d427b342"
contract = "VAnchor"
deployed-at = 3573943
linked-anchors = [
    { type = "Evm", chain = "goerli", chain-id = 5, address = "0x885c8b5f580e08780e9eb8ad1f43dd51c88743ac" },
    { type = "Evm", chain = "sepolia", chain-id = 11155111, address = "0x2f31776767859e6907aebce3f60572d921188d2f" },
    { type = "Evm", chain = "optimism", chain-id = 420, address = "0xa7f45216a24acfe9bb514a9c7d08f4e442d75a04" },
]

[evm.moonbase.contracts.events-watcher]
enabled = true
polling-interval = 1000
print-progress-interval = 7000

[evm.moonbase.contracts.proposal-signing-backend]
node = "tangle"
type = "DKGNode"

[evm.moonbase.contracts.withdraw-config]
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x5B8D80"

[[evm.moonbase.contracts]]
address = "0x2369f7169067f2ad59c3d0eb1bb57b6268cc2475"
contract = "SignatureBridge"
deployed-at = 3573912

[evm.moonbase.contracts.events-watcher]
enabled = true
polling-interval = 1000
print-progress-interval = 7000